require('dotenv').config(); // Used dotenv to load environment variables from a .env file into process.env

const express = require('express'); // Used express as the server. Backend framework for Node.js
const bodyParser = require('body-parser'); // Used body-parser to parse incoming request bodies in a middleware before the handlers
const cors = require('cors'); // Added later since I was getting Axios: Network Error
const { GoogleGenerativeAI } = require('@google/generative-ai'); // Used Google Generative AI to generate responses

const app = express(); 
const port = process.env.PORT || 3000; 

app.use(bodyParser.json());
app.use(cors()); // Added later since I was getting Axios: Network Error

const apiKey = process.env.GOOGLE_API_KEY;
const genAI = new GoogleGenerativeAI(apiKey);

const model = genAI.getGenerativeModel({
    model: 'gemini-1.5-pro',
});

const generationConfig = {
    temperature: 0.7,
    topP: 0.95,
    topK: 64,
    maxOutputTokens: 8192,
    responseMimeType: 'text/plain',
};

app.post('/chat', async (req, res) => {
    const userMessage = req.body.message;

    // Generated responses using Google Generative AI structured prompt

    const parts = [
      {text: "Don't answer questions that are not related to food nutrition and health. \nThis chatbot mainly focuses on Sri Lankan people so try to incorporate more information that are related to Sri Lankan nutrition and food items.\nDon't mention ' That's a great question to ask your doctor or a registered dietitian!'. \nMake sure to mention that 'Disclaimer: This chatbot is designed to provide general information and support. It is not a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider for any health-related questions or concerns you may have.' at the end of every answer related to food nutrition and health you provide. \nMake the response short but in a way that it conveys all the important details. \nPraise the user for researching about food nutrition related stuff and encourage them to learn more.\nWhen giving healthy eating tips make it unique and randomized and the tips should be generally good ones."},
      {text: "I suffer from high blood sugar. What are foods that are not good for me to eat?"},
      {text: "For high blood sugar, limit high-GI foods like sugary drinks, refined carbs, starchy veggies, and some sweet fruits. Also watch processed foods, fried foods, red meat, and full-fat dairy. Consult a doctor or registered dietitian for a personalized plan."},
      {text: "I have diabetes, is honey good for me to eat?"},
      {text: "Sure. While honey is natural, it still raises blood sugar due to its sugar content. Consult your doctor or dietitian for advice on incorporating honey, if at all, into your diabetes management plan. Focus on moderation and monitor blood sugar levels."},
      {text: "What are the nutritional benefits of eating spinach?"},
      {text: "Spinach is a leafy green loaded with vitamins A, C, and K, essential for vision, immunity, and bone health. It also provides iron, fiber, and antioxidants, all in a low-calorie package. Including spinach in your diet is a simple way to boost your overall health."},
      {text: "How many calories are in a medium-sized apple?"},
      {text: "A medium-sized apple (around 3 inches in diameter) typically contains between 95 and 104 calories. It's important to remember that this is just an estimate and the exact number of calories can vary depending on the specific apple variety and its size."},
      {text: "Is quinoa a good source of protein?"},
      {text: "Yes, quinoa is a good source of plant-based protein. Here's a breakdown:\n\nOne cup (185 grams) of cooked quinoa contains about 8 grams of protein.\nIt's a complete protein, meaning it contains all nine essential amino acids your body can't produce on its own. This is uncommon for plant-based proteins.\n\nHowever, some experts argue that quinoa is a \"nearly complete\" protein because it contains lower amounts of certain essential amino acids, like lysine. Regardless, it's still a valuable source of protein, especially for those following plant-based diets."},
      {text: "What vitamins can I get from eating oranges?"},
      {text: "Oranges are famous for their vitamin C, but that's not all! They also provide folate (important for cell growth) and small amounts of B vitamins for energy and cellular function."},
      {text: "What are some healthy snacks that I can eat on a low-carb diet?"},
      {text: "Sure, here's a list of low-carb snack options:\n\nVeggies with dips: Celery, cucumber, peppers with guac or hummus.\nBerries: Low-sugar and antioxidant-rich.\nHard-boiled eggs: Protein-packed and portable.\nNuts & seeds: Healthy fats and protein, watch portions.\nDeviled eggs: Low-carb mayo or mustard base, protein-rich.\nPork rinds (no heavy seasonings): Protein and healthy fats, zero carbs.\nGuac with low-carb veggies: Bell peppers, celery, zucchini.\nLow-carb protein bars (check ingredients list).\n\nEnjoy these in moderation as part of a balanced low-carb diet!"},
      {text: "Can you suggest a balanced meal plan for weight loss?"},
      {text: "Here's a version of the balanced meal plan for weight loss:\n\nSample Meal Plan (adjust portions as needed):\n\nBreakfast (300-400 cal): Greek yogurt with berries & nuts OR eggs with spinach & whole-wheat toast.\n\nLunch (400-500 cal): Grilled chicken, brown rice, roasted veggies, side salad.\n\nSnack (150-200 cal): Apple slices with nut butter OR carrot sticks with hummus.\n\nDinner (500-600 cal): Baked salmon, quinoa, steamed broccoli & cauliflower.\n\nSnack (optional, 100-150 cal): Nuts OR Greek yogurt with cinnamon.\n\nFocus on whole foods, portion control, and all food groups. Consult a doctor or dietitian for a personalized plan.\nRemember, this is a sample. Explore different options to keep meals interesting!"},
      {text: "What foods should I avoid if I have higah cholesterol?"},
      {text: "Here's a take on foods to avoid for high cholesterol:\n\nLimit saturated fat: fatty meats, full-fat dairy, fried foods, baked goods (coconut/palm oil too).\nAvoid trans fats: processed foods, fried foods, margarine (check labels).\nReduce added sugars: sugary drinks, refined carbs, candy.\nFocus on: lean protein, whole grains, fruits & veggies, healthy fats (avocados, nuts, seeds, olive oil).\n\nConsult a doctor or dietitian for a personalized plan."},
      {text: "How can I increase my daily fiber intake?"},
      {text: "Here's a take on boosting your daily fiber intake:\n\nEat more fruits, veggies, whole grains & legumes: These are all-star fiber sources.\nMake smart swaps: Opt for whole-wheat options, add veggies to meals, and choose fiber-rich snacks.\nIncrease gradually: Avoid digestive discomfort by slowly upping your fiber intake.\nDrink plenty of water: Fiber needs water for proper digestion.\n\nFocus on incorporating these tips throughout your meals and snacks for a more fiber-rich diet!"},
      {text: "What’s a good breakfast option that’s high in protein?"},
      {text: "Here are some protein-packed breakfast options to fuel your morning:\n\nGreek Yogurt Parfait: Easy and layered with protein, fiber, and antioxidants.\nHard-boiled Eggs: Portable, protein-rich, and customizable.\nProtein Smoothie: Refreshing blend with Greek yogurt, protein powder, fruits, and milk.\nFor a more involved option, try scrambled eggs with smoked salmon on whole-wheat toast, or a cottage cheese bowl with fruit and nuts.\n\nRemember to adjust portion sizes and explore different protein sources to find your favorites!"},
      {text: "Can you suggest a meal plan for someone with diabetes?"},
      {text: "Sure, creating a diabetic meal plan requires personalization. Here's the key:\n\nFocus on low-glycemic index (GI) foods and balance carbs with protein and healthy fats.\nPortion control is crucial.\nInclude all food groups for a balanced intake of nutrients.\nConsult a doctor or dietitian for a personalized plan.\n\nSample Diabetic Meal Ideas:\n\nBreakfast: Whole-wheat toast with eggs, Greek yogurt with berries, oatmeal with nuts.\nLunch: Salad with grilled chicken, lentil soup, tuna salad sandwich on whole-wheat bread.\nDinner: Baked salmon with roasted veggies, chicken stir-fry with brown rice, vegetarian chili.\nSnacks: Almonds with apple slices, carrots with hummus, cottage cheese with berries.\n\nRemember: Read food labels, stay hydrated, limit sugary drinks, plan meals, and be consistent!"},
      {text: "What are some quick and healthy lunch ideas for work?"},
      {text: "Sure, here's a quicker rundown of Sri Lankan work lunch ideas:Prep ahead: \n\nKiribath with Isso Wade, Yellow Rice with Dhal Curry, Fish Curry with String Hoppers, or Chicken Kottu Roti (using leftovers).\nQuick options: Eggplant Salad with Pol Roti, Yellow Gram Salad, or Yogurt & Fruit Bowl with Granola.\n\nTips: Utilize leftovers, prep veggies in advance, make condiments in bulk, and pack an insulated lunch bag.\n\nEnjoy delicious and healthy Sri Lankan lunches at work!"},
      {text: "What foods can help manage my blood sugar levels?"},
      {text: "Here's ar take on blood sugar management through diet:\n\nFocus on Low-GI choices: Non-starchy veggies, whole grains, moderate fruits, legumes, healthy fats.\nInclude lean protein and Greek yogurt for added benefits.\nLimit refined carbs, sugary drinks, fried foods, processed meats.\n\nConsult a doctor or dietitian for a personalized plan.\n\nRemember: Portion control is key, combine with a balanced diet and exercise for optimal management."},
      {text: "What should I eat to boost my immune system?"},
      {text: "Sure, here's a take on boosting your immune system through diet:\n\nEat a rainbow: Fruits & veggies provide vitamins, minerals, and antioxidants to fight free radicals.\nInclude lean protein, whole grains, and healthy fats.\nIncorporate probiotics (yogurt, kefir) for gut health.\nStay hydrated! Water is crucial for overall health.\nLimit processed foods, added sugar, and unhealthy fats.\nFocus on sleep and manage stress.\n\nThis isn't a magic bullet, but it can give your immune system a good foundation!"},
      {text: "How can I modify my diet to reduce inflammation?"},
      {text: "Here's a take on reducing inflammation through diet:\n\nEat more:\n\nColorful fruits & veggies\nFatty fish (omega-3s)Whole grains\nHealthy fats (olive oil, nuts)\n\nEat less:\n\nRed meat & processed meats\nRefined carbs (sugary drinks, white bread)\nTrans fats (fried foods, processed snacks)\nAdded sugar\n\nBonus: Spices (turmeric, ginger), fiber, moderate alcohol, stay hydrated.\n\nConsult a doctor or dietitian for a personalized plan!\n\nFocus on these changes for an anti-inflammatory diet that can improve your health."},
      {text: "What are some dietary recommendations for someone with IBS?"},
      {text: "Sure, here's a version of dietary recommendations for IBS:\n\nRegular meals, manage stress, stay hydrated.\nLimit: High-FODMAP foods (like apples, broccoli, dairy), sugary drinks, processed foods.\nIdentify triggers: Keep a food journal to pinpoint IBS culprits.\nInclude: Low-FODMAP options (like berries, spinach, lean protein), healthy fats.\nGradual reintroduction: Consider a low-FODMAP diet with a doctor or dietitian to identify triggers.\nProbiotics: May help, discuss with your doctor.\n\nConsult a doctor or dietitian for a personalized plan based on your needs."},
      {text: "Is it okay to eat eggs every day?"},
      {text: "Sure. Eggs daily are generally safe for healthy adults (1-2 daily). They offer protein and vitamins, and dietary cholesterol minimally impacts blood cholesterol compared to saturated and trans fats. If you have heart disease or high cholesterol, limit egg intake (consult a doctor)."},
      {text: "What’s the difference between saturated and unsaturated fats?"},
      {text: "Sure. Here's a take on saturated vs. unsaturated fats:\n\nSaturated fats: Solid at room temp, raise bad cholesterol. Sources: red meat, full-fat dairy, coconut oil.\n\nUnsaturated fats: Liquid at room temp, better for you. Two types:\nMonounsaturated (olive oil, avocado) lowers bad cholesterol and raises good cholesterol.\nPolyunsaturated (fish, nuts) lowers bad cholesterol and reduces inflammation.\n\nFocus on unsaturated fats for a heart-healthy diet."},
      {text: "How much protein should I consume daily?"},
      {text: "Sure, here's a shorter version on daily protein needs:\n\nDepends on weight, age, activity level, health.\nAdults: 0.8 grams/kg body weight (minimum).\nActive adults: 1.1-1.5 grams/kg.\nAthletes: Up to 1.7 grams/kg.\nConsult a doctor or dietitian for personalized needs.\n\nFocus on a balanced diet with protein sources alongside fruits, vegetables, and whole grains."},
      {text: "Are there any health benefits to drinking green tea?"},
      {text: "Green tea is rich in antioxidants and may offer benefits like improved brain function, weight management, heart health, and even dental health. While more research is needed, it's generally safe for most people. Consider consulting a doctor before regular consumption, especially if you have health concerns or take medications."},
      {text: "What should I eat before and after a workout?"},
      {text: "Sure, here's a version of the pre and post-workout meal info:\n\nPre-workout (30-60 min before):\nLight, easily digestible snack with carbs & protein.\nExamples: Banana with nut butter, oatmeal with berries.\n\nPost-workout (within 1 hour):\nCarbs & protein to refuel and repair muscle.\nExamples: Protein shake with fruit, chicken with brown rice & veggies.\n\nAdjust based on your needs and consult a dietitian for personalization."},
      {text: "Can you suggest a high-protein, low-fat snack?"},
      {text: "Here are some high-protein, low-fat snack options:\n\nHard-boiled eggs, Greek yogurt, edamame, string cheese with pear slices, carrot sticks with hummus.\nFor more involvement: Turkey slices with cucumber (protein wrap), cottage cheese with peppers, DIY trail mix (control ingredients), roasted chickpeas, protein smoothie (almond milk, protein powder, spinach).\n\nFocus on lean protein and limit added fats/sugars. Enjoy!"},
      {text: "How can I stay hydrated during exercise?"},
      {text: "Here's a guide to staying hydrated during exercise:\n\nDrink before, during, and after: Aim for 17-20 ounces of water 2-3 hours before starting. Sip every 15-20 minutes during your workout, adjusting for intensity and sweat rate.\nListen to your thirst: Don't wait until you're parched. Consider a sports drink for longer or intense workouts.\nMonitor urine color: Aim for pale yellow.\n\nRemember, proper hydration is key for optimal exercise performance and recovery."},
      {text: "What are the best foods for muscle recovery?"},
      {text: "Here's a take on muscle recovery foods:\n\nFocus on lean protein (chicken, fish, eggs) within 2 hours of your workout for muscle repair. Aim for 20-40 grams.\nPair protein with carbs (sweet potato, brown rice) to replenish energy stores. Adjust intake based on workout intensity.\nInclude healthy fats (avocado, nuts) for sustained energy and nutrient absorption.\nBonus: Tart cherry juice, watermelon, or chocolate milk may offer additional recovery benefits.\n\nRemember, this is a general guideline. Consult a doctor or dietitian for personalized advice."},
      {text: "What are some gluten-free breakfast options?"},
      {text: "Here's a version of gluten-free breakfast options:\n\nQuick & Easy: Fruit & nut butter, smoothie, chia pudding.\nMore Involved: Gluten-free oatmeal, pancakes/waffles, scrambled eggs with veggies.\nSri Lankan Inspired: Kiribath, string hoppers with veggies, yellow coconut rice.\n\nFor all options, prioritize certified gluten-free ingredients and adjust toppings/sides as desired. Enjoy!"},
      {text: "What are the signs of a food allergy?"},
      {text: "Food allergies cause various symptoms soon after eating (minutes) or hours/days later. Common signs include:\n\nSkin: Hives, itching, eczema (around mouth)Stomach: Nausea, vomiting, diarrhea, cramps\nRespiratory: Wheezing, coughing, trouble breathing\nMouth/Throat: Tingling/itching, swelling\n\nSeek immediate medical attention if you experience these symptoms, especially if they worsen quickly. This could be a sign of a severe allergic reaction (anaphylaxis).\n\nIf you suspect a food allergy, see a doctor or allergist for diagnosis and management."},
      {text: "How can I ensure I get enough nutrients on a vegan diet?"},
      {text: "Sure, here's a shorter take on ensuring nutrients on a vegan diet:\n\nEat a rainbow of fruits & veggies, whole grains, legumes, nuts & seeds for variety.\nFocus on plant-based protein sources like soy, quinoa, lentils & beans.\nChoose fortified plant-based milk and consider a vitamin B12 supplement.\nPlan meals, cook at home, and consult a dietitian for guidance.\n\nBy following these tips, you can get the nutrients you need to thrive on a vegan diet!"},
      {text: "Can you give me a healthy eating tip for today?"},
      {text: "Here's a shorter tip for today, June 13 2024: Aim for a rainbow! Include at least 5 servings of fruits & veggies from various colors throughout the day. It's a great way to boost your vitamin and antioxidant intake!"},
      {text: "How can I avoid late-night snacking?"},
      {text: "Sure, here's a version on avoiding late-night snacking:\n\nIdentify your trigger: Boredom, habit, or genuine hunger? Address the root cause.\nEat regularly: Don't skip meals, have a healthy pre-dinner snack, and stay hydrated.\nPlan & prep: Plan meals and snacks to avoid unhealthy choices later.\nNighttime routine: Establish a relaxing routine that doesn't involve food.\nTemptation control: Brush your teeth after dinner and limit tempting snacks at home.\n\nBe patient and consistent! Consult a dietitian if needed for personalized help."},
      {text: "What are some ways to stay motivated on my diet?"},
      {text: "Here's a version of tips to stay motivated on your diet:\n\nSet SMART goals (Specific, Measurable, Achievable, Relevant, Time-bound).\nCelebrate progress, not perfection. Stay positive and focus on how you feel.\nMake it enjoyable! Explore new recipes, find healthy alternatives to favorites.\nFind support: Tell friends/family, join a support group, or consult a dietitian.\nReward yourself with non-food rewards for reaching goals.\n\nBonus tips: Plan meals, keep healthy snacks on hand, drink water, get enough sleep, manage stress.\n\nRemember, it's a journey! These strategies will help you stay motivated for long-term success."},
      {text: "How can I improve my gut health?"},
      {text: "Here's a take on improving gut health:\n\nEat more fiber-rich fruits, veggies, and whole grains.\nIncorporate fermented foods or consider prebiotic supplements to feed gut bacteria.\nManage stress, get enough sleep, exercise regularly.\nLimit processed foods, sugar, unhealthy fats, alcohol, and unnecessary antibiotics.\n\nThese lifestyle changes can significantly improve your gut health over time. Remember, consistency is key!  Consult a doctor for personalized advice if needed."},
      {text: "What are some good sources of antioxidants?"},
      {text: "Sure! Here's a list of antioxidant sources:\n\nFruits & Veggies: Berries, citrus fruits, leafy greens, colorful veggies\nWhole Grains: Brown rice, quinoa, oats\nNuts & Seeds: Almonds, walnuts, chia seeds\nDark Chocolate (moderation!)Beverages (moderation): Green tea, coffee\n\nEat a rainbow! Variety is key to maximizing antioxidants in your diet."},
      {text: "What should I eat to improve my skin health?"},
      {text: "Here's a take on promoting healthy skin through diet:\n\nEat plenty of fruits & veggies, especially citrus fruits, berries & leafy greens for vitamins & antioxidants.\nInclude fatty fish like salmon for omega-3s and healthy fats from nuts & seeds for hydration and elasticity.\nStay hydrated with water! Green tea can also be beneficial.\nLimit processed foods, sugar, and excessive alcohol as they can worsen skin health.\n\nFocus on a balanced diet rich in these ingredients and consult a doctor or dermatologist for personalized advice."},
      {text: "Can you suggest foods that help with mental clarity and focus?"},
      {text: "Sure, here's a shorter take on foods for mental clarity and focus:\nEat foods rich in omega-3s, choline, B vitamins, and antioxidants.\nExamples: fatty fish, blueberries, nuts, dark chocolate (at least 70% cocoa), Greek yogurt, avocados.\nConsider following the Mediterranean or DASH diet for brain health.\nRemember, a balanced diet, hydration, sleep, and stress management are all important for mental clarity and focus."},
      {text: "Is brown rice healthier than white rice?"},
      {text: "Brown rice is generally healthier than white rice because it's a whole grain. It retains the bran and germ layers, containing more fiber, vitamins, minerals, and antioxidants than processed white rice. This makes brown rice more nutritious and potentially better for blood sugar management."},
      {text: "What’s the difference between Greek yogurt and regular yogurt?"},
      {text: "Sure. Here's a take on Greek yogurt vs. regular yogurt:\n\nGreek yogurt: Strained for thicker texture, higher protein, lower sugar (plain), but less calcium. Great for protein boost or using in recipes like dips.\nRegular yogurt: More calcium, thinner consistency, can be higher in sugar (check labels). Better choice if prioritizing calcium intake.\n\nBoth are versatile! Choose based on your needs: protein, calcium, or texture."},
      {text: "How does almond milk compare to cow’s milk nutritionally?"},
      {text: "Almond milk is lower in calories and fat than cow's milk, but also lower in protein and most micronutrients. Unsweetened versions typically have less sugar than cow's milk.\n\nChoose cow's milk for protein and calcium.\nChoose fortified almond milk if you need calcium and a lower-calorie option, but can't tolerate lactose."},
      {text: "Which is better for weight loss: whole wheat bread or white bread?"},
      {text: "Here's a take on whole wheat vs. white bread for weight loss:\n\nWhole wheat wins: Higher fiber for fullness, more nutrients, and lower glycemic index for steadier blood sugar.\nBut moderation matters: Both breads fit in a weight loss plan if portion-controlled. Focus on a balanced diet with fruits, veggies, and lean protein for overall success."},
      {text: "What foods are allowed on the keto diet?"},
      {text: "Sure, here's a rundown of keto-friendly foods:\n\nMeat, poultry, fatty fish\nEggs\nNon-starchy veggies (leafy greens, broccoli, etc.)\nHealthy fats (avocados, olive oil, nuts, seeds)\nSmall berries (limited amounts)\nFull-fat dairy (moderation)\n\nFoods to limit: grains, starchy veggies, sugary fruits, legumes, sugary drinks, processed foods.\n\nConsult a doctor or registered dietitian before starting keto."},
      {text: "Can you provide a sample meal plan for a Sri Lankan diet?"},
      {text: "Absolutely! Here's a sample Sri Lankan meal plan for a day, focusing on variety and showcasing some staple dishes:\n\nBreakfast (7:00 AM):\n\nKiribath (Milk Rice): A creamy rice dish made with coconut milk and rice. It's naturally gluten-free and can be enjoyed plain or with sweet toppings like raisins or cashews.\nSri Lankan Black Tea or Coffee:  Enjoy your tea or coffee black or with a touch of coconut milk for a local twist.\n\nLunch (1:00 PM):\n\nYellow Rice with Dhal Curry: This vibrant yellow rice is cooked with turmeric and spices, often served with a protein-rich lentil dhal curry. You can add other vegetables like carrots, green beans, or eggplant for extra flavor and nutrients.\nPol Sambol:  A spicy and flavorful coconut relish made with grated coconut, red onions, chilies, and lime juice. It adds a delicious kick to the rice and dhal.\nFresh Papaya Slices: A refreshing and healthy end to your lunch.\n\nSnack (4:00 PM):\n\nIsso Wade (Fried Lentil Fritters):  These crispy fritters are made with masoor dal (red lentils), onions, and spices. They are a popular Sri Lankan snack and can be enjoyed with a coconut chutney for dipping.\nKing Coconut Water: A natural source of electrolytes and hydration, perfect for a refreshing afternoon pick-me-up.\n\nDinner (7:00 PM):\n\nString Hoppers (Idiyappa) with Fish Curry:  These thin rice noodles are steamed and served with a flavorful fish curry, made with coconut milk, spices, and your choice of fish.\nWambatu Moju (Roasted Eggplant Curry): This is a traditional Sri Lankan side dish made with roasted eggplant simmered in a fragrant curry sauce.\nSalad with a Simple Vinaigrette: A light and refreshing salad with local greens like baby spinach or kale helps balance the richness of the curries.\n\nDessert (Optional):\n\nWattalapam: This creamy custard dessert is made with eggs, milk, sugar, and spices like cardamom and cloves. It's a delicious and light way to end your meal.\n\nPlease note: This is just a sample, and there are endless variations for each meal.  Feel free to adjust portion sizes, ingredients, and spice levels to your preferences. You can also explore other Sri Lankan dishes like Kottu Roti (shredded flatbread stir-fry), Chicken Curry, and Lamprais (banana leaf wrapped rice with curries)."},
      {text: "What are the key components of a paleo diet?"},
      {text: "Sure, here's a version of the key components of a Paleo diet:\n\nPaleo Diet: Mimic what hunter-gatherers ate.\n\nEat:\nLean meat, fish, eggs\nVegetables, some fruits\nNuts, seeds, healthy fats\n\nAvoid:\n\nGrains, legumes, dairy\nProcessed foods, sugar, additives\n\nFocus:\n\nWhole, unprocessed foods\nMore protein, moderate fat, lower carbs\n\nConsult a doctor or dietitian before starting."},
      {text: "How do I start an intermittent fasting routine?"},
      {text: "Sure, here's a take on starting intermittent fasting (IF):\n\nStart Slow: Choose a method (16/8 or 5:2) and gradually extend fasting windows.\n\nHydrate & Eat Well: Drink plenty of water during fasting and focus on whole foods during eating windows.\n\nListen to Your Body: Break the fast if excessively hungry or unwell. Consult a doctor before starting IF, especially if you have health conditions."},
      {text: "Should I take a multivitamin daily?"},
      {text: "Daily multivitamins can be helpful for people with limited diets or specific needs, but not everyone needs them. Focus on a balanced diet first. Discuss with your doctor if a multivitamin is right for you, considering your individual health and dietary habits."},
      {text: "What are the benefits of taking omega-3 supplements?"},
      {text: "Omega-3 supplements offer potential benefits for heart, brain, eye health, and inflammation. They may also support mood. Focus on a balanced diet with fatty fish first. Consult your doctor about dosage and if supplements are right for you, especially if you have health conditions or take medications."},
      {text: "How can I naturally increase my vitamin D levels?"},
      {text: "Sure, here's a take on boosting vitamin D levels naturally:\n\nSun exposure: Aim for 15-30 minutes of midday sun (without sunburn) for your body to produce vitamin D.\n\nDiet: Include fatty fish, egg yolks, UV-exposed mushrooms, and fortified foods like milk and cereals.\n\nConsult your doctor: Discuss vitamin D levels and if a supplement is right for you."},
      {text: "What are the best foods for iron absorption?"},
      {text: "Here's a take on boosting iron absorption:\n\nEat iron-rich foods: lean meat, fish, beans, lentils, dark leafy greens.\nPair plant-based iron with vitamin C sources (citrus, peppers) for better absorption.\nLimit calcium (dairy, fortified foods) and coffee/tea around iron-rich meals.\n\nConsult a doctor if you have iron deficiency concerns. They can recommend the best approach for you."},
      {text: "How much water should I drink each day?"},
      {text: "Sure, here's on daily water intake:\n\nAdults: Aim for around half your body weight in ounces of water daily.\nChildren: Needs vary by age, but generally range from 40-113 ounces daily.\nFactors that influence water needs: Activity level, health conditions, pregnancy/breastfeeding.\nListen to your body: Thirst is a good indicator, dark urine can signal dehydration.\nConsult a doctor for personalized advice, especially with health conditions."},
      {text: "Are there benefits to drinking herbal teas?"},
      {text: "Sure, here's a take on herbal teas:\n\nRelaxation, Digestion, Immunity: Chamomile, peppermint, echinacea teas may offer these benefits.\nAntioxidants: Many herbal teas are rich in antioxidants.\nHydration: Enjoy herbal teas alongside water for added flavor.\n\nConsult a doctor before consuming herbal teas, especially if you have health conditions or are pregnant/breastfeeding."},
      {text: "What are the signs of dehydration?"},
      {text: "Dehydration happens when you lose more fluids than you consume. Here are key signs:\n\nThirst:  Your body's first signal.\nLess frequent urination: Darker colored urine due to less water.\nFatigue, dizziness: Less energy and lightheadedness due to lack of fluids for body functions.\nDry mouth and skin: Less saliva production and dry feeling.\nHeadaches: Dehydration can trigger headaches.\n\nDrink plenty of water, eat water-rich fruits/vegetables, and limit sugary drinks/alcohol to stay hydrated!"},
      {text: "Can you recommend some hydrating foods?"},
      {text: "Sure, here's a list of hydrating foods:\n\nFruits & Veggies: Watermelon, strawberries, cantaloupe, cucumber, celery, tomatoes, leafy greens - all above 90% water!\nSoups & Broths: Vegetable or chicken noodle soup provide hydration and electrolytes.\nYogurt & Cottage Cheese: Opt for low-fat or fat-free options for added hydration and protein.\n\nRemember, water is still key! Aim for 8 glasses (64 ounces) daily and adjust based on your needs."},
      {text: "How can I control my sugar cravings?"},
      {text: "Sure, here's a version on controlling sugar cravings:\n\nIdentify triggers: Emotional eating, habit, dehydration? Find healthier coping mechanisms.\nEat regularly: Don't skip meals, focus on whole foods, limit processed foods.\nGet enough sleep, manage stress.\nDrink green tea: May help regulate blood sugar.\nPlan meals, keep healthy snacks on hand, brush your teeth.\n\nCravings are tough, but these tips can help! Consult a doctor or dietitian if needed."},
      {text: "What are some healthy alternatives to junk food?"},
      {text: "Sure, here's a take on healthy junk food alternatives:\n\nCraving Crunchy? Baked kale chips, roasted chickpeas, veggie sticks with hummus, air-popped popcorn with herbs, or whole-wheat crackers.\nCraving Sweet? Dark chocolate, frozen yogurt with berries, baked apples with nut butter, fruit salad with Greek yogurt, or homemade energy bites.\nCraving Salty? Baked sweet potato fries, roasted chickpeas, or air-popped popcorn with nutritional yeast.\nCraving Comforting? Whole-wheat pizza with veggies, lean turkey burger on a whole-wheat bun, or whole-wheat pasta with roasted veggies and a light cheese sauce.\n\nFocus on whole foods, plan your meals, and don't deprive yourself. Enjoy these alternatives to curb cravings without sacrificing health!"},
      {text: "What foods help to keep you full longer?"},
      {text: "Sure, here's a take on foods that keep you full:\n\nHigh-fiber foods: Whole grains, legumes, fruits, and veggies. Fiber slows digestion for lasting fullness.\nLean protein: Chicken, fish, beans, lentils. Protein takes longer to digest than carbs, keeping you satisfied.\nHealthy fats: Avocados, nuts, seeds, olive oil. Slow gastric emptying for sustained fullness.\nLow GI foods: Whole grains, legumes, some fruits and veggies. Cause gradual blood sugar rise, preventing hunger crashes.\n\nThese foods can help you feel full and potentially reduce calorie intake. Focus on a balanced diet that incorporates them for long-term success."},
      {text: "How can I manage my appetite throughout the day?"},
      {text: "Sure, here's a version of tips to manage your appetite throughout the day:\n\nPlan meals & snacks: Avoid unhealthy choices by planning balanced meals and healthy snacks throughout the day.\nPrioritize satiating foods: Focus on fiber-rich options like fruits, veggies, whole grains, lean protein, and healthy fats to keep you feeling full for longer.\nStay hydrated: Drink plenty of water to avoid mistaking thirst for hunger. Limit sugary drinks that can lead to hunger crashes.\nMindful eating: Slow down, savor your food, and avoid distractions while eating to promote mindful eating habits.\n\nRemember, consistency is key! Implement these strategies for effective appetite management and a healthier approach to eating."},
      {text: "What are some healthy cooking methods?"},
      {text: "Sure, here's a take on healthy cooking methods:\n\nSteaming, boiling, poaching: Gentle methods to preserve nutrients in veggies, fish, eggs.\nBaking, roasting: Use minimal oil for meats, veggies, and some fruits.\nStir-frying: Quick and healthy with a small amount of oil for flavorful dishes.\nGrilling: Great for meats and veggies, but avoid charring.\nMicrowaving (limited use): Can be healthy for reheating or steaming.\n\nBonus tips: Healthy fats like olive oil, minimal added salt, and minimal cooking liquid all contribute to healthy cooking!"},
      {text: "How can I reduce the sodium content in my meals?"},
      {text: "Sure, here's a version on reducing sodium in meals:\n\nFresh is best: Choose fresh or frozen vegetables, poultry, fish over canned. Season with herbs, spices, citrus juices instead of salt.\nRinse canned items: Reduce sodium in canned goods by rinsing.\nCook smart: Limit processed ingredients, don't add salt at the table.\nBuild flavor with acid, umami, healthy fats.\nReduce gradually: Your taste buds will adjust over time.\n\nThese tips can significantly lower sodium intake without sacrificing flavor!"},
      {text: "What are the benefits of meal prepping?"},
      {text: "Here's a take on meal prepping benefits:\n\nSaves time and money with grab-and-go meals.\nPromotes portion control and healthy choices.\nReduces food waste and boosts variety in your diet.\nLowers stress and improves consistency in healthy eating."},
      {text: "Can you suggest some easy ways to add vegetables to my diet?"},
      {text: "Here are some quick hacks to boost your veggie intake:\n\nSneaky Swaps: Riced cauliflower in rice dishes, zoodles for pasta.\nVeggie Boosters: Add chopped veggies to omelets, smoothies, soups.\nSnacking Smart: Veggie sticks with hummus, frozen edamame, trail mix with veggie chips.\nSalads with a Twist: Jar salads, roasted veggie salads, rainbow salads.\n\nThese simple tips can pack a nutritious punch!"},
      {text: "What are some healthy options when eating at a fast-food restaurant?"},
      {text: "Sure, here's a version of healthy fast-food options:\n\nChoose grilled protein (chicken, fish) over fried options.\nOpt for salads or wraps with whole-wheat bread/tortillas and light dressings.\nSkip sugary drinks and large portions.\nLook for healthy-ish options like grilled chicken sandwiches or salad bowls.\n\nFast food isn't ideal, but these tips can help you make healthier choices in a pinch."},
      {text: "How can I stick to my diet while dining out?"},
      {text: "Sticking to your diet while dining out requires planning and smart strategies. Here's the gist:\n\nBefore you go: Research menus, plan your order.\nAt the restaurant: Ask questions, prioritize protein & veggies, go easy on sauces, customize your dish, opt for healthy drinks, and practice mindful eating.\n\nRemember, indulgence is okay! Focus on progress, not perfection."},
      {text: "What should I look for on a restaurant menu to make healthy choices?"},
      {text: "Here's a version for navigating menus:\n\nSeek out: grilled, baked, whole-wheat, lean protein, veggies, healthy fats, light sauces/dressings, smaller portions.\nAvoid: fried, creamy, cheesy, loaded, hidden sugars.\nAsk questions, customize, start with salad/soup.\n\nThese tips help you choose healthy options while dining out!"},
      {text: "How can I navigate social gatherings without overeating?"},
      {text: "Sure, here's a shorter version:\n\nPre-party snack: Curb hunger with a healthy snack before the event.\nHydrate: Water fills you up and reduces mistaking thirst for hunger.\nStrategic positioning: Stand away from food displays if possible.\nFocus on conversation: Engage with others to avoid mindless snacking.\nMindful plate: Fill half with veggies, a quarter with protein, and a quarter with whole grains.\nSavor & Listen: Eat slowly and stop when comfortably full.\nPolite declines: Say \"no thanks\" to unwanted food.\nHealthy choices: Opt for grilled/baked dishes, lean protein, and colorful vegetables.\n\nSocial gatherings are about connection, not just food! Focus on enjoying company and mindful eating."},
      {text: " "},
      { text: userMessage },
    ];

    try {
        const result = await model.generateContent({
            contents: [{ role: 'user', parts }],
            generationConfig,
        });
        console.log("Running model")
        return res.json({ response: result.response.text });
        console.log('Generated content:', result);
        // return res.json({ response: "This is working"})
        // console.log('Generated content:', result.response.text);
    } catch (error) {
        console.error('Error generating content:', error);
        res.status(500).json({ response: 'Sorry, something went wrong.' });
        //console.log('Error generating content:', error);
    }
});

app.listen(port, () => {
    console.log(`Server is running on http://172.22.2.92:${port}`); // http://YOUR_IP_ADDRESS:

});
